### ISSUE TITLE
End-to-end RAG tutorial using source file, PyAirbyte and Pinecone (using Langchain)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#19] opened 2024-05-16 22:56 UTC
## Summary
The goal is to show users how to use PyAirbyte to load data from  `file`  source, store the data in `Pinecone` vector store and perform a short RAG demo (using OpenAI/LangChain) on the loaded data in `Pinecone`. 

## Deliverable
Python notebook illustrating end to end RAG using PyAirbyte, `file` as source, and `Pinecone` as destination. Please add a "What / Why / How" blurb at the top of the notebook to explain what the code is doing.

## Resources to Assist

- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- File source documentation: https://docs.airbyte.com/integrations/sources/file
- LangChain Pinecone support: https://python.langchain.com/v0.1/docs/integrations/vectorstores/pinecone/

**Comment by Harmaton** [comment] 2024-06-03 04:39
I have done this before, I would like to write about it :)

**Comment by siddhant3030** [comment] 2024-06-03 05:48
I'd like to work on this with real use case for a client

**Comment by marcosmarxm** [comment] 2024-06-03 13:39
@siddhant3030 It is yours. @Harmaton I assigned other to you.

**Comment by marcosmarxm** [comment] 2024-06-10 13:28
@siddhant3030 do you need any help herE?

**Comment by marcosmarxm** [comment] 2024-06-20 16:39
@siddhant3030 can you give us an update about this task?

**Comment by pangeran-bottor** [comment] 2024-06-20 20:11
Hi, I would love to take this if it becomes available

**Comment by siddhant3030** [comment] 2024-06-22 20:48
@marcosmarxm I'm working on this issue. But I'm having a difficulty connection to pinecone destination. and I'm getting this error  and I'm not sure if its because of timezone bec I'm in India and in pinecone the aws is available in us-east-1

`HTTPSConnectionPool(host='controller.us-east-1.pinecone.io', port=443): Max retries exceeded with url: /databases/1024 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff642cb130>: Failed to resolve 'controller.us-east-1.pinecone.io' ([Errno -2] Name or service not known)")) Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn sock = connection.create_connection( File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name or service not known The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 791, in urlopen response = self._make_request( File "/usr/local/lib/python3.9/site-`

this is what I tried let me know what I can do

<img width="685" alt="Screenshot 2024-06-23 at 2 18 02 AM" src="https://github.com/airbytehq/PyAirbyte-Hackathon/assets/9019958/cfbeff4a-de95-48d7-b174-60b586a905c9">

**Comment by pangeran-bottor** [comment] 2024-06-23 04:05
@ siddhant3030 It will benefit all of us if you reply and update or share the problem here so others and the Airbyte team can also check for transparency. From the outside, this seems inactive for three weeks, so others probably can pick up this issue

**Comment by siddhant3030** [comment] 2024-06-23 05:23
@marcosmarxm I'll try to submit the PR by tomorrow. Thanks

**Comment by siddhant3030** [comment] 2024-06-23 05:28
@marcosmarxm please go ahead and assign it to @pangeran-bottor

**Comment by gupta-arpan** [comment] 2024-06-24 04:16
@siddhant3030  If you have been unable to address the issue, could you please transfer it to me?

**Comment by siddhant3030** [comment] 2024-06-24 04:20
@gupta-arpan please go ahead. I can't reassign it

**Comment by bala-ceg** [comment] 2024-06-24 04:40
I would like to take this issue, just in case if it is available

**Comment by pangeran-bottor** [comment] 2024-06-24 05:27
@marcosmarxm, per your last information, can I take the issue if this is available?

**Comment by gupta-arpan** [comment] 2024-06-24 05:30
@bindipankhudi, As @siddhant3030 gave me a gohead signal. I have made a PR https://github.com/airbytehq/quickstarts/pull/124 for this issue please review it, Thanks.

**Comment by marcosmarxm** [comment] 2024-06-24 14:21
@gupta-arpan the user @pangeran-bottor requested this issue before. It is his right to work on this.

**Comment by pangeran-bottor** [comment] 2024-06-28 22:27
Hi guys @bindipankhudi @aaronsteers @marcosmarxm 
Kindly need your help to review this https://github.com/airbytehq/quickstarts/pull/127

**Closed** 2024-07-09 00:08 UTC
